### ISSUE TITLE
Can you provide experimental results of (resnet18 inspired by SimplePose)? 

### ISSUE THREAD

**Issue by wy3406** [ThomasDelteil/MultiPoseEstimation_MXNet#1]
Hi,
first, thank you very much for your code.then, the experimental results of the (resnet18 inspired by SimplePose) on the valdataset can be provided.It would be better if the model could be provided.
Tks

**Comment by ThomasDelteil** [comment]
Hi @wy3406,

GluonCV has released a lot of resnet based SimplePose implementation with better results than the ones I had obtained: https://gluon-cv.mxnet.io/model_zoo/pose.html

The models are available directly through gluoncv, see this tutorial for example: https://gluon-cv.mxnet.io/build/examples_pose/demo_simple_pose.html

**Comment by wy3406** [comment]
thank you for your reply.
